services:
  core:
    build:
      args:
        - BASE_IMAGE=ubuntu:latest
        - PROJECT_NAME=core
        - USER_NAME=user
        - PYTHON_VERSION=3.11
        - UID=${HOST_UID-1000}
        - GID=${HOST_GID-1000}
        - RUN_POETRY_INSTALL_AT_BUILD_TIME=true
      context: ../../
      dockerfile: docker/Dockerfile
    volumes:
      - ../../:/home/user/core
    ports:
      - 8000:8000
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    tty: true
    shm_size: 2gb